services:
  database:
    image: 'immotep-database'
    container_name: immotep-database
    restart: unless-stopped
    build: ./database
    env_file:
      - ./database/.env
    volumes:
      - /Users/flo/Documents/Compose/CM_IMMO_BACKEND/data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    networks:
      - immotep-network
  
  api:
    image: 'immotep-api'
    container_name: immotep-api
    restart: unless-stopped
    build: ./api
    env_file:
      - ./api/.env
    links:
      - database:database
    depends_on:
      - database
    ports: 
      - 3000:3000
    networks:
      - immotep-network
      
  cloudflared:
    container_name: ${CLOUDFLARED_CONTAINER_NAME}
    image: ${CLOUDFLARED_IMAGE}
    command: ${CLOUDFLARED_COMMAND}
    restart: unless-stopped
    networks:
      - immotep-network
  
  immotep-object-storage:
    image: ${OBJECT_STORAGE_IMAGE}
    container_name: ${OBJECT_STORAGE_CONTAINER_NAME}
    ports:
      - "${OBJECT_STORAGE_PORT_9000}:${OBJECT_STORAGE_PORT_9000}"
      - "${OBJECT_STORAGE_PORT_9001}:${OBJECT_STORAGE_PORT_9001}"
    expose:
      - ${OBJECT_STORAGE_PORT_9000}
      - ${OBJECT_STORAGE_PORT_9001}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_OPTS: ${MINIO_OPTS}
    volumes:
      - ./immotep-object-storage:/data
    command: server --console-address ":${OBJECT_STORAGE_PORT_9001}" /data
    networks:
      - immotep-network

networks:
  immotep-network:
    name: 'immotep-network'
    driver: bridge
    external: true
