FROM debian:12.5

# Installs openssh-server package
RUN apt-get update && apt-get install -y openssh-server

# Creates sftp_user
RUN useradd -rm -d /home/sftp_user -s /bin/bash -G sudo -u 10001 sftp_user 
RUN echo "sftp_user:SFTPUSERPASSWORDHERE" | chpasswd 

# Necessary sshd file
RUN mkdir /var/run/sshd

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

# Setup directory for sftp
RUN mkdir -p /var/sftp/uploads
RUN chown root:root /var/sftp
RUN chmod 755 /var/sftp
RUN chown sftp_user:sftp_user /var/sftp/uploads

# Allows sftp connection but disables connection through ssh
RUN echo '\n\
Match User sftp_user  \n\
ForceCommand internal-sftp \n\ 
PasswordAuthentication yes \n\ 
ChrootDirectory /var/sftp \n\ 
PermitTunnel no  \n\ 
AllowAgentForwarding no \n\ 
AllowTcpForwarding no \n\ 
X11Forwarding no ' >> /etc/ssh/sshd_config 
